Add new functions
colinj/TDateTimeHelper pull request #1
Opened 2020-09-03 15:39 UTC by MaiconSoft

Add UnixTime property;
Add Parse string as custom string;
Add ParseLocal to parse using local string like 'en-US';
All functions has test implemented.

2020-09-04 13:43 UTC, colinj requested changes
Thank you @MaiconSoft for making this PR for adding `UnixTime` and `TotalSeconds`. Unfortunately, I can't accept these changes as they are because it would break the principle of mutating a value type. I've provided comments explaining what is required to be changed to follow the principle.

Also could you please remove the changes to the lines of code which are not part of this PR.
I hope you consider making those changes as I would really like to accept this PR eventually.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +    procedure SetUnixTime(const Value: Int64);
As stated in the 'README.md` file:

> An important rule ... is that TDateTime is a value type and therefore is **immutable**. This means all helper methods will create and **return a new value** and **not change the current value** of the calling TDateTime variable (unless explicitly assigned).

The philosophy of the TDateTimeHelper is that we don't modify the existing value but create a brand new value by using a class function.

Instead of the setter procedure `SetUnixTime`, turn it into a public class function (see class function Create). You could possibly call it class function `CreateUnixTime(const Value: Int64): TDateTime; static; inline;`.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +    procedure SetTotalSecounds(const Value: Int64);
Same as `SetUnixTime`, make `SetTotalSecounds` a class function in the public section. Make sure you spell `seconds` correctly. The class function can be `CreateTotalSeconds(const Value: Int64): TDateTime; static; inline;`

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +    function Parse(Date: string; aFormat: string = ''; aDateSeparator: Char = #0;
Make `Parse` a class function similar to `class function Create`. This function should always return a new value and not modify the instance's value.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +    function ParseLocal(Date: string;local:string=''):TDateTime; inline;
Treat `ParseLocal` as the same as `Parse`. Make this a class function.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +    property UnixTime: Int64 read GetUnixTime write SetUnixTime;
`TDateTimeHelper` properties can only be read-only. Please remove the setter `write SetUnixTime`.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +    property TotalSecounds: Int64 read GetTotalSecounds write SetTotalSecounds;
The spelling should be `TotalSeconds` and please remove the setter.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +    function WithinYears(const aDateTime: TDateTime; const aYears: Integer):
Avoid changing the formatting of these lines since this is not part of the PR

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +    function InRange(const aStartDateTime, aEndDateTime: TDateTime; const
Please don't change the formatting. This is not part of the PR.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +    class function Create(const aYear, aMonth, aDay: Word): TDateTime; overload;
Please don't change the formatting. This is not part of the PR.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> -    function WithinYears(const aDateTime: TDateTime; const aYears: Integer): Boolean; inline;
Please keep this formatting unless you are making real changes to these functions.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +  Result := Trunc(86400 * self);
Rename `self` to `Self` to keep formatting standards. Please make sure all instances of 'self' is also renamed to 'Self'

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +function TDateTimeHelper.InRange(const aStartDateTime, aEndDateTime: TDateTime;
Please don't change the formatting. This is not part of the PR.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +procedure TDateTimeHelper.SetTotalSecounds(const Value: Int64);
As mentioned above, we don't modify the value of existing instance. Instead this setter function needs to be turned into a class function that returns new value. 

```
class function CreateTotalSeconds(const Value: Int64);
begin
  Result := (Value / 86400);
end;
```

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +procedure TDateTimeHelper.SetUnixTime(const Value: Int64);
Replace setter procedure into a class function and change it from `Self` to `Result`.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +function TDateTimeHelper.Parse(Date: string; aFormat: string = ''; aDateSeparator: Char = #0;
Make this into a class function and don't use `Date` as an argument as it can be ambiguous to the Delphi `Date` function. Rename it as 'aDate' where the prefix `a` stands for "argument".

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +    self := StrToDateTime(Date);
Do not update `Self`. Just assign value to `Result`.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +  Self := StrToDateTime(Date, fs);
Do not assign to `Self` but return value via `Result`

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +function TDateTimeHelper.ParseLocal(Date: string; local: string = ''):TDateTime;
Treat 'ParseLocal' the same  as `Parse`.

2020-09-04 13:43 UTC, colinj commented on DateTimeHelper.pas
> +  Self := StrToDateTime(Date, fs);
Don't set 'Self'. Only set `Result`

2020-09-07 14:29 UTC, MaiconSoft commented
Hi Colinj, sorry about that, i not realize this rule, but i am open for all changes needed for help your project. Thank you

2020-09-29 00:59 UTC, merged

2020-09-29 00:59 UTC, colinj commented
Thank you @MaiconSoft